### ISSUE TITLE
About splits.pth

### ISSUE THREAD

**Issue by barisbatuhan** [cvlab-columbia/expert#6]
Is it possible that you provide more information on the content of splits.pth? I am trying to create a custom dataset to run your model but I cannot figure out what some individual elements stand for in this specific file.

**Comment by surisdi** [comment]
Hi @barisbatuhan , `splits.pth` is a python dictionary that can be loaded using `torch.load('splits.pth')`, and contains information about training and test splits, vocabulary, action ids, and other information used in the dataloader. See [this line](https://github.com/cvlab-columbia/expert/blob/b7b89b2c96ce05dd0eb73d2cd6536e4235f62fed/datasets.py#L45) and the following ones to see how it is used. 
It is basically a way of separating clips of actions into training and testing splits, so that everyone has access to the same splits. But it is specific to the Epic Kitchens dataset, so if you are creating a custom dataset and you prefer to use a different format (different from what we used for `splits.pth`), it may be more convenient (the format we used is very specific for Epic Kitchens).
